In [91]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [92]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [93]:
median_bedrooms = df.bedrooms.median()
median_bedrooms

4.0

In [94]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [95]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [96]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [97]:
model.intercept_

221323.00186540384

In [98]:
model.predict([[5000,4,10]])

/home/darshil929/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([842873.5528015])

In [99]:
import pickle

In [100]:
with open('multiple_regression','wb') as f:
    pickle.dump(model,f)

In [101]:
with open('multiple_regression','rb') as f:
    mp = pickle.load(f)

In [102]:
mp.predict([[5000,4,10]])

/home/darshil929/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([842873.5528015])